### ISSUE TITLE
Major update of tasks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#1803]
> Feedback will be welcome, but we are currently still working on this plan.

---

The plan below aims at reaching these high-level goals:

1. It introduces `TaskGroupV2` collections of `TaskV2`s.
2. It fully revamps the access-control rules for tasks and task groups, going from the current `owner/username` matching to using database relationships.
3. It makes it possible to non-disruptively revoke a user's access to a task, even after the user already used that task (ref #1744).

A few parts are still partly undefined, either because they are TBD or because we'd rather postpone them to a different update. The main undefined areas are:

4. Task lifecycle - this is clearly postponed to a different update.
5. How are attributes precisely distributed into `TaskV2` vs `TaskGroupV2`
    - [ ] #1828
    - [ ] #1829
    - [ ] #1831
6. How is the identity of tasks or task groups defined, in two areas:
    a. What kind of checks prevent/allow two independent collections of the same task package by two different users? Are they based on folder paths, on `TaskGroupV2` metadata, or on something else?
    b. Is the `TaskV2.source` still a suitable attempt towards a unique task identifier? This is relevant both for point `a` above and for how to make tasks portable across different fractal-server instances.
7. Will we able to fully drop/upgrade the current `owner/username` access-control logic? Or do we need to remain backwards compatible.
8. How will we handle v1 tasks? Ideally we'd like to not modify teir data structure and access-control rules at all; if this would introduce too much friction, then we'll have to make changes to V1 tasks as well.

# Database structure

## Tasks and task groups

- [x] We add a new model `TaskGroupV2`, with its new table `taskgroupv2`.
- [x] We include an _optional_ foreign key `taskv2.taskgroupv2_id` -> this means that all tasks must belong to a group (even if the group size is one).
- [x] ~~FUTURE RELEASE: We make the FK required~~ POSTPONED - ref #1837
- [x] We include a ORM attribute `TaskGroupV2.task_list`, with cascade delete (deleting a task group also deletes all its tasks).

## Tasks and users or user groups

- [x] Required foreign key `taskgroupv2.user_id`.
- [x] Optional foreign key `taskgroupv2.user_group_id`.
- [x] ~~Test that when a `UserGroup` is deleted, all corresponding `taskgroupv2.user_group_id` values are set to `None`.~~ Show that you cannot delete a `UserGroup` if it is linked to a `TaskGroupV2`, but you have to manually perform "cascade" operations and set FKs to None.

## `update-db-data` script

This set of changes will certainly come with a corresponding `fractalctl update-db-data` script.
- [ ] #1836

# API changes and definition of access control rules

The new API for task groups will live at `/api/v2/task_group/{task_group_id}/`, and some existing endpoints (e.g. those in `/api/v2/task/`) will also change.

## Who can create a task group and how?

- [x] No one can create a task group directly via the API.
- [x] Every endpoint that creates tasks (e.g. when POST-ing a single task or upon task collection) creates a task group and establishes the relationship with the new tasks.
- [x] LATER: Every endpoint that creates tasks accepts a request-body parameter that determines the usergroup to associate to the new tasks. This can be one of three options: no group, a specific group, the "All" group.
- [x] Setting `taskgroupv2.user_group_id` to a certain id is successful only if `taskgroupv2.user_id` belongs to that group.

### Implementation steps
- [x] The single-task POST endpoint should create a `TaskGroupV2` db entry and establish the association with the new `TaskV2`
    - [x] `user_id` is the one of the user making the API request
    - [x] `user_group_id` is the one of the All group - for the moment
    - [x] LATER/TBD : `user_group_id` is an request query parameter (not yet defined how to pass the argument through the API)
- [x] The same logic applies to the local task-collection endpoint
- [x] The same logic applies to the ssh task-collection endpoint
- [x] The same applies to the custom task-collection endpoint
- [x] For testing, the `task_factory_v2` should create a `TaskGroupV2` for each task that it creates. Note that we need to add an `user_id` argument to `task_factory_v2`, to be used when creating the task group.

### Who can GET an existing task group?

- [x] The user in `taskgroupv2.user_id`.
- [x] Any user in group `taskgroupv2.user_group_id` (if set).
- [x] No other user (Unauthorized response).

#### Some details

- [x] Let's add a new GET-task-group endpoint, e.g. at `/api/v2/task-group/{id}`
- [x] The task-group-list `GET /api/v2/task-group/` should return only the task groups to which the current user has read access.
- [ ] #1842
- [x] review precise form of access-control queries
- ~~TBD:  maybe add `GET /api/v2/task-group/?includes_groups=False` that does not include task groups where access is because of group membership~~ moved to #1839 
- ~~TBD: maybe add `GET /api/v2/task-group/?exclude_non_active=True`~~ moved to #1839 

### Who can PATCH a `TaskGroupV2` "standard" attribute (i.e. `TaskGroupV2.active`) via the API?

- [x] The user in `taskgroupv2.user_id`.
- [x] No other user (Unauthorized response).

### Who can PATCH a `TaskGroupV2` association to individual tasks (i.e. `TaskGroupV2.task_list`) via the API?

- [x] No one, the association between tasks and task groups is immutable.

### Who can PATCH a `TaskGroupV2` owner (i.e. `TaskGroupV2.user_id`) via the API?

- [x] No one, this operation is forbidden.

### Who can PATCH a `TaskGroupV2` association to a `UserGroup` via the API?

- [x] The user in `taskgroupv2.user_id`.
- [x] No other user (Unauthorized response).

#### Some details

- [x] The `TaskGroupUpdateV2` schema should have a `user_group_id: Optional[None] = None` field
- [x] If `user_group_id` is not set, no action should be taken (this can be addressed through `exclude_unset=True`)
- [x] If `user_group_id` is set to an integer, we should
    - [x] check that this corresponds to an existing user group
    - [x] check that `taskgroupv2.user_id` belongs to that group.
    - [x] set the foreign key accordingly
- [x] If `user_group_id` is set to `None`, the db entry should be made null -> this is a supported behavior

### Who can DELETE a `TaskGroupV2` via the API?

- [x] The user in `taskgroupv2.user_id`.
- [x] No other user (Unauthorized response).
- [x] Note: deleting a `TaskGroupV2` also includes bulk deletion of all tasks in the group.
- [x] Note: This deletion cannot go through if it would break some existing DB relationship (that is, if any of the group tasks is in use in a workflow).

### How does the POST of a single task change?

The creation of a task also leads to the creation of a taskgroup. Here we describe to which usergroup the taskgroup should belong.

- [x] #1827
- [x] EDIT: let's have two optional and mutually-exclusive query params: `user_group_id: Optional[int] = None` and `private: bool = False`. This adds one more case to the ones below: if user_group_is is not None and private -> 422
- [x]  `user_group_id` is not set, the POST endpoint should fetch and use the default-group ID (that is, the taskgroup should belong to the `All` group)
- [x] If `user_group_id` is set to an integer, we should
    - [x] check that this corresponds to an existing user group
    - [x] check that `taskgroupv2.user_id` belongs to that group.
    - [x] set the foreign key of the taskgroup accordingly
- [x] If `user_group_id` is set to `None`, the db entry should be made null -> this is a supported behavior

### How does the POST of multiple tasks change?

This is the same as the POST of a single task (re: which usergroup should own the task group)

- [x] Local task collection
- [x] SSH task collection
- [x] Custom task collection

### Who can GET a single task?

- [x] Anyone who can GET the corresponding task group.
- [x] No other user (Unauthorized response).

### How does `GET /api/v2/tasks/` change?

- [x] It will return only tasks to which the current users has access, either because they are the task-group owner or because they belong to the task-group user group.
- [x] We have two different endpoints with different formats (e.g. at `/api/v2/task/` and `/api/v2/task_group/`). This one here (the tasks one) returns a flat list of tasks.

### Who can DELETE a `TaskV2` via the API?

- [x] No one, in principle, as we should not change the identity of which tasks belong to which task groups. This feature is available through the task-group DELETE endpoint.

## Workflow API

- [x] Introduce `WorkflowReadV2WithWarnings`, which is the same as `WorkflowReadV2` but uses WorkflowTaskReadV2WithWarning`
- [x] Introduce `WorkflowTaskReadV2WithWarning`, which is the same as `WorkflowTaskReadV2` but with an additional `warnings: Optional[str]` field
- [x] Modify the `GET /api/v2/workflow/{id}/` endpoint, so that it returns a `WorkflowReadV2WithWarnings` object
- [x] Modify the `GET /api/v2/workflow/{id}/` endpoint, so that it iterates over all `WorkflowTask`s and fills in their `warning` field if appropriate, that is:
    - [x] If the user has no access to the task: `warning = "Current user has no access to this task"`
    - [x] If the task is not active: `warning = "This task is not active"`
- [x] This can in principle be achieved with `_get_task_read_access` within a try/except block, where we can recognize whether the error was a 403 or a 422. If it is not sufficiently robust, we can recompute this information directly from within the endpoint.

### Who can POST a workflowtask into a workflow

- [x] Only users who could GET the corresponding task.

#### Details

- [x] If a task is associated to an `active=False` taskgroup, it cannot be added to a workflow
- [x] To do: test these two new features above

### Who can run a Workflow which includes a given task?

- [x] Only users who could GET all the corresponding tasks.
- [x] No other user (Unauthorized response).

#### Details

- [x] If the workflow includes a task to which I have no access --> 422
- [x] If the workflow includes a non-active task --> 422
- [x] This only concerns the subset of tasks between the first and the last to be executed, not all the workflow tasks. - @ychiucco 0

# Description of loss of access

Now tracked in https://github.com/fractal-analytics-platform/fractal-server/issues/1840

**Comment by jluethi** [comment]
Thanks for writing up the great summary @tcompa 

> Will we able to fully drop/upgrade the current owner/username access-control logic? Or do we need to remain backwards compatible.

Let's list anything that would stop us doing that. I'm strongly in favor of dropping it.
High-level: 
1. Only admins can currently delete tasks, so I'm not worried about keeping access of some users to e.g. task editing of existing tasks.
2. All current tasks are visible to everyone anyway

> How will we handle v1 tasks? Ideally we'd like to not modify their data structure and access-control rules at all; if this would introduce too much friction, then we'll have to make changes to V1 tasks as well.

We anyway deprecate running V1 workflows. If we keep an admin way to remove the envs (could also be manually removing env folders), we don't need to maintain V1 task ownerships in >2.5.0 server releases. We can deactivate relevant endpoints if that helps.

>  Create task groups and make sure that each existing task belongs to one of them - TBD how to define the associations (that is, whether we want the task groups to also work as the ones created in the future would).

If they do, that could be great. The thing I want to achieve (as admin) is being able to deactivate (& reactivate) old tasks

> To rephrase it: we are stating that the access-control rules should not apply to the read operation for something you already had access to in the past.

Agreed!
And interface-wise, it would be great to handle this similarly to how deactivated tasks will be handled.

**Comment by jluethi** [comment]
> b. Is the TaskV2.source still a suitable attempt towards a unique task identifier? This is relevant both for point a above and for how to make tasks portable across different fractal-server instances.

Anything collected for group ALL: Nobody can collect the same version of this task again => this wouldn't be done via source, but via task metadata
Generally moving away from source seems reasonable to me

Portability:
Can we export more structured metadata? Yes
Would allow for more structured imports (e.g. package name needs to match, version can be more flexible if needed, Python version likely shouldn't matter)


Backwards compatibility to import old workflows?
We keep source in place, but we stop relying on it. We can keep the source-based import for the moment (e.g. look for structured metadata upon import. If not available, look for source and use old import)


=> We keep the source around (in old tasks & supporting the import), but we stop using it as the default way to figure out tasks
New tasks don't need to have source anymore

**Comment by tcompa** [comment]
To add:
- [ ] Include metadata for active/non-active status of tasks, to set the stage for task/venvs lifecycle work.

**Comment by tcompa** [comment]
All currently-open items here were moved to separate issues. Closing.
