### ISSUE TITLE
Handle parsl dependency and backend

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-server#306]
I propose to proceed this way:
- [x] parsl remains an optional dependency for fractal, but we modify its source, to point to upstream parsl (rather than our custom fork, as it does at the moment). In this way, we can get the server back to pypi and close https://github.com/fractal-analytics-platform/fractal-server/issues/137.
- [x] We leave the backend `_parsl` folder in the repository, but we add a `NotImplementedError` at its root, with a detailed message where:
    - [x] We link to https://github.com/fractal-analytics-platform/fractal-server/issues/94 and https://github.com/Parsl/parsl/issues/2452, and mention that because of this issue one would need to use our custom fork rather than mainstream parsl.
    - [x] We also mention that a stress test failed (https://github.com/fractal-analytics-platform/fractal-server/issues/224) and we never fixed it.
- [x] We make sure that tests depending on parsl are skip-marked by pytest, e.g. by simply not installing the parsl extra.
